import wabizabi

EXPECTED_PUBLIC_EXPORTS = {
    "Agent",
    "AsyncFunctionTool",
    "AfterResponseHook",
    "AfterToolCallHook",
    "BeforeRequestHook",
    "BeforeToolCallHook",
    "Capability",
    "DocumentPart",
    "FinishReason",
    "FunctionTool",
    "Handoff",
    "HandoffEvent",
    "HandoffResult",
    "ImagePart",
    "InMemoryTelemetryRecorder",
    "HistoryProcessor",
    "Hooks",
    "MessageHistory",
    "Model",
    "ModelMessage",
    "ModelProfile",
    "ModelRequest",
    "ModelResponse",
    "ModelResult",
    "ModelCapabilityError",
    "ModelSettings",
    "NativeOutputPart",
    "NoopTelemetryRecorder",
    "OutputConfig",
    "OutputDecoder",
    "OutputDecodingError",
    "OutputEvent",
    "OutputMode",
    "OutputValidationError",
    "ReasoningChunkEvent",
    "ReasoningPart",
    "RefusalPart",
    "RequestEvent",
    "RequestPart",
    "ResponseEvent",
    "ResponsePart",
    "RetryFeedbackPart",
    "RunContext",
    "RunEvent",
    "RunResult",
    "RunState",
    "RunUsage",
    "StaticCapability",
    "StreamedRun",
    "SystemInstructionPart",
    "TelemetryRecorder",
    "PrepareToolsHook",
    "TextChunkEvent",
    "TextPart",
    "TrimHistoryProcessor",
    "TrimOldestRequestsProcessor",
    "Tool",
    "ToolCallEvent",
    "ToolCallPart",
    "ToolDefinition",
    "ToolError",
    "ToolInvocationError",
    "ToolNotFoundError",
    "ToolResultEvent",
    "ToolReturnPart",
    "Toolset",
    "UserPromptPart",
    "__version__",
    "define_async_function_tool",
    "define_function_tool",
    "define_static_capability",
    "json_output_config",
    "schema_output_config",
    "text_output_config",
    "tool",
    "tool_output_config",
    "tool_plain",
}


def test_version_is_defined() -> None:
    assert wabizabi.__version__ == "0.1.0"


def test_root_public_exports_match_v1_surface() -> None:
    assert set(wabizabi.__all__) == EXPECTED_PUBLIC_EXPORTS
    for name in EXPECTED_PUBLIC_EXPORTS:
        assert hasattr(wabizabi, name)
